/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  h5c3: [
    'h5c3',
    {
      type: 'autogenerated',
      dirName: 'HTML&CSS'
    }
  ],
  javascript: [
    'javascript',
    {
      type: 'autogenerated',
      dirName: 'javascript'
    }
  ],
  react: [
    'react',
    {
      type: 'autogenerated',
      dirName: 'react'
    }
  ],
  vue: [
    'vue',
    {
      type: 'autogenerated',
      dirName: 'vue'
    }
  ],
  typescript: [
    'typescript',
    {
      type: 'autogenerated',
      dirName: 'typescript'
    }
  ],
  mst: [
    {
      type: 'autogenerated',
      dirName: '杂项'
    }
  ],
  liunx: [
    'liunx',
    {
      type: 'autogenerated',
      dirName: 'liunx'
    }
  ]
};

module.exports = sidebars;
